import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import { pool } from './db.js';

dotenv.config();
const app = express();
const PORT = Number(process.env.PORT || 3000);
const JWT_SECRET = process.env.JWT_SECRET || 'dev-only-change-me';
app.use(cors({ origin: process.env.CORS_ORIGIN ? process.env.CORS_ORIGIN.split(',').map(x=>x.trim()) : true }));
app.use(express.json());
function tokenFor(user){return jwt.sign({sub:user.id,role:user.role,username:user.username},JWT_SECRET,{expiresIn:'12h'});}
async function auth(req,res,next){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Kirish talab qilinadi'});req.user=jwt.verify(h.slice(7),JWT_SECRET);next();}catch{res.status(401).json({error:'Sessiya yaroqsiz yoki tugagan'});}}
function plateData(b){const allowed=['01','10','20','25','30','40','50','60','70','75','80','85','90','95'];const r=String(b.regionCode||''),f=String(b.firstLetter||'').toUpperCase(),n=String(b.number||''),l=String(b.lastLetters||'').toUpperCase();if(!allowed.includes(r)||!/^[A-Z]$/.test(f)||!/^[0-9]{3}$/.test(n)||!/^[A-Z]{2}$/.test(l))throw Error('Avtomobil raqami noto‘g‘ri');return{r,f,n,l,plate:`${r} ${f} ${n} ${l}`};}
app.get('/api/health',async(_q,res)=>{try{await pool.query('SELECT 1');res.json({ok:true,database:true});}catch{res.status(503).json({ok:false,database:false});}});
app.post('/api/auth/register',async(req,res)=>{const{fullName,username,password}=req.body;if(!fullName||!username||!password||password.length<6)return res.status(400).json({error:'Ism, login va kamida 6 belgili parol kerak'});try{const h=await bcrypt.hash(password,12),q=await pool.query('INSERT INTO users(full_name,username,password_hash) VALUES($1,$2,$3) RETURNING id,full_name,username,role',[fullName.trim(),username.trim(),h]);res.status(201).json({user:q.rows[0],token:tokenFor(q.rows[0])});}catch(e){res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Bu login mavjud':'Ro‘yxatdan o‘tishda xatolik'});}});
app.post('/api/auth/login',async(req,res)=>{try{const q=await pool.query('SELECT * FROM users WHERE username=$1',[String(req.body.username||'').trim()]);if(!q.rows[0]||!(await bcrypt.compare(req.body.password||'',q.rows[0].password_hash)))return res.status(401).json({error:'Login yoki parol noto‘g‘ri'});const u={id:q.rows[0].id,full_name:q.rows[0].full_name,username:q.rows[0].username,role:q.rows[0].role};res.json({user:u,token:tokenFor(u)});}catch{res.status(500).json({error:'Kirishda xatolik'});}});
app.get('/api/settings',auth,async(_q,res)=>{const q=await pool.query('SELECT hourly_rate,minimum_payment,calculation_mode FROM settings WHERE id=1');res.json({hourlyRate:Number(q.rows[0].hourly_rate),minimumPayment:Number(q.rows[0].minimum_payment),calculationMode:q.rows[0].calculation_mode});});
app.put('/api/settings',auth,async(req,res)=>{const h=Number(req.body.hourlyRate),m=Number(req.body.minimumPayment);if(!Number.isFinite(h)||h<=0||!Number.isFinite(m)||m<0)return res.status(400).json({error:'Narx noto‘g‘ri'});const mode=req.body.calculationMode==='minute'?'minute':'hour';const q=await pool.query('UPDATE settings SET hourly_rate=$1,minimum_payment=$2,calculation_mode=$3,updated_at=NOW() WHERE id=1 RETURNING hourly_rate,minimum_payment,calculation_mode',[h,m,mode]);res.json({hourlyRate:Number(q.rows[0].hourly_rate),minimumPayment:Number(q.rows[0].minimum_payment),calculationMode:q.rows[0].calculation_mode});});
app.get('/api/sessions/active',auth,async(_q,res)=>{const q=await pool.query(`SELECT s.id,v.plate,v.model,v.driver_name,s.started_at,s.hourly_rate,s.calculation_mode FROM sessions s JOIN vehicles v ON v.id=s.vehicle_id WHERE s.status='active' ORDER BY s.started_at`);res.json(q.rows);});
app.post('/api/sessions/start',auth,async(req,res)=>{let p;try{p=plateData(req.body);}catch(e){return res.status(400).json({error:e.message});}const c=await pool.connect();try{await c.query('BEGIN');let v=(await c.query('SELECT * FROM vehicles WHERE plate=$1',[p.plate])).rows[0];if(!v)v=(await c.query('INSERT INTO vehicles(region_code,first_letter,number,last_letters,plate,model,driver_name) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *',[p.r,p.f,p.n,p.l,p.plate,req.body.model||null,req.body.driverName||null])).rows[0];const s=(await c.query('SELECT hourly_rate,minimum_payment,calculation_mode FROM settings WHERE id=1')).rows[0];const x=(await c.query('INSERT INTO sessions(vehicle_id,hourly_rate,minimum_payment,calculation_mode) VALUES($1,$2,$3,$4) RETURNING id,started_at',[v.id,s.hourly_rate,s.minimum_payment,s.calculation_mode])).rows[0];await c.query('COMMIT');res.status(201).json({id:x.id,plate:p.plate,startedAt:x.started_at});}catch(e){await c.query('ROLLBACK');res.status(e.code==='23505'?409:500).json({error:e.code==='23505'?'Bu avtomobil hozir jarayonda':'START bajarilmadi'});}finally{c.release();}});
app.post('/api/sessions/:id/finish',auth,async(req,res)=>{const c=await pool.connect();try{await c.query('BEGIN');const q=await c.query(`SELECT s.*,v.plate FROM sessions s JOIN vehicles v ON v.id=s.vehicle_id WHERE s.id=$1 AND s.status='active' FOR UPDATE`,[req.params.id]);if(!q.rows[0]){await c.query('ROLLBACK');return res.status(404).json({error:'Faol sessiya topilmadi'});}const s=q.rows[0],end=new Date(),sec=Math.max(0,Math.floor((end-new Date(s.started_at))/1000)),min=sec/60,raw=s.calculation_mode==='minute'?min*Number(s.hourly_rate)/60:Math.max(1,Math.ceil(min/60))*Number(s.hourly_rate),amount=Math.max(Number(s.minimum_payment),raw),u=await c.query('UPDATE sessions SET finished_at=$1,duration_seconds=$2,amount=$3,status=\'completed\' WHERE id=$4 RETURNING id,started_at,finished_at,duration_seconds,amount',[end,sec,amount,s.id]);await c.query('COMMIT');res.json({...u.rows[0],plate:s.plate,amount:Number(u.rows[0].amount)});}catch{await c.query('ROLLBACK');res.status(500).json({error:'FINISH bajarilmadi'});}finally{c.release();}});
app.get('/api/reports/daily',auth,async(req,res)=>{const date=/^\d{4}-\d{2}-\d{2}$/.test(req.query.date||'')?req.query.date:new Date().toISOString().slice(0,10),q=await pool.query(`SELECT v.plate,s.started_at,s.finished_at,s.duration_seconds,s.amount FROM sessions s JOIN vehicles v ON v.id=s.vehicle_id WHERE s.status='completed' AND s.started_at::date=$1 ORDER BY s.started_at DESC`,[date]);const summary=q.rows.reduce((a,x)=>({count:a.count+1,seconds:a.seconds+Number(x.duration_seconds||0),amount:a.amount+Number(x.amount||0)}),{count:0,seconds:0,amount:0});res.json({date,summary,rows:q.rows});});
app.get('/api/dashboard',auth,async(_q,res)=>{const q=await pool.query(`SELECT COUNT(*) FILTER(WHERE status='active')::int active,COUNT(*) FILTER(WHERE status='completed' AND started_at::date=CURRENT_DATE)::int today_count,COALESCE(SUM(duration_seconds) FILTER(WHERE status='completed' AND started_at::date=CURRENT_DATE),0)::bigint today_seconds,COALESCE(SUM(amount) FILTER(WHERE status='completed' AND started_at::date=CURRENT_DATE),0)::numeric today_amount FROM sessions`);const r=q.rows[0];res.json({active:r.active,todayCount:r.today_count,todaySeconds:Number(r.today_seconds),todayAmount:Number(r.today_amount)});});
app.listen(PORT,()=>console.log(`AVTODROM API running on :${PORT}`));
