import { readFile } from 'node:fs/promises';
const frontendFile=new URL('../frontend/index.html',import.meta.url);
const PATCH=String.raw`<script id="avtodrom-final-fix">
(function(){'use strict';
function $(id){return document.getElementById(id)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v??'').trim().toLocaleLowerCase('uz').replace(/\s+/g,' ')}
async function apiCall(path,opt){
  if(typeof window.api==='function')return window.api(path,opt);
  const t=localStorage.getItem('avtodrom_token')||'';const h=Object.assign({'Content-Type':'application/json'},t?{Authorization:'Bearer '+t}:{},opt?.headers||{});const r=await fetch('/api'+path,{...(opt||{}),headers:h});const tx=await r.text();let d={};try{d=tx?JSON.parse(tx):{}}catch{d={error:tx}}if(!r.ok)throw Error(d.error||('HTTP '+r.status));return d;
}
async function studentAuto(){
 const type=$('type'),school=$('school'),group=$('group'),student=$('student'),sid=$('studentId');if(!type||!school||!group||!student||!sid)return;if(student.dataset.finalFix)return;student.dataset.finalFix='1';let cache=[];let timer=0;
 async function load(){const d=await apiCall('/students'+(school.value?'?schoolId='+encodeURIComponent(school.value):''));cache=(Array.isArray(d)?d:(d.rows||[])).slice().sort((a,b)=>norm(a.full_name).localeCompare(norm(b.full_name),'uz',{sensitivity:'base'}));return cache}
 async function apply(){const q=norm(student.value);if(!q){sid.value='';return}if(!cache.length)await load();let pool=school.value?cache.filter(s=>String(s.school_id||'')===String(school.value)):cache;const exact=pool.filter(s=>norm(s.full_name)===q);const m=exact.length?exact:pool.filter(s=>norm(s.full_name).includes(q));if(m.length!==1){sid.value='';return}const s=m[0];student.value=s.full_name||'';sid.value=s.id||'';if(s.school_id){school.value=String(s.school_id);if(typeof window.groupsForSchool==='function')try{await window.groupsForSchool()}catch{}}if(s.group_id){group.value=String(s.group_id);group.disabled=true}if(typeof window.studentInfo==='function')try{window.studentInfo()}catch{}}
 type.addEventListener('change',()=>{if(type.value==='school'){student.disabled=false;group.disabled=true;group.innerHTML='<option value="">Guruh o‘quvchidan avtomatik aniqlanadi</option>';load().catch(()=>{})}});student.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>apply().catch(()=>{}),220)});student.addEventListener('change',()=>apply().catch(()=>{}));student.addEventListener('blur',()=>{if(student.value.trim())apply().catch(()=>{})});
}
function seconds(v){const x=new Date(v?.started_at||0).getTime();return Number.isFinite(x)&&x>0?Math.max(0,(Date.now()-x)/1000):Number(v?.duration_seconds||0)}
function money(n){return new Intl.NumberFormat('uz-UZ').format(Math.round(Number(n)||0))+' so‘m'}
function dur(s){s=Math.max(0,Math.floor(Number(s)||0));return [Math.floor(s/3600),Math.floor(s/60)%60,s%60].map(x=>String(x).padStart(2,'0')).join(':')}
function amount(v){if(String(v?.customer_type||'').toLowerCase()==='school'||v?.student_id)return 0;const m=Number(v?.manual_price);if(m>0)return m;const r=Number(v?.hourly_rate||0),min=Number(v?.minimum_payment||0);return Math.max(min,r>0?r*seconds(v)/3600:Number(v?.amount||0))}
async function find(id){let a=Array.isArray(window.active)?window.active:[],v=a.find(x=>String(x.id)===String(id));if(v)return v;try{const d=await apiCall('/sessions/active');a=Array.isArray(d)?d:(d.rows||[]);return a.find(x=>String(x.id)===String(id))||null}catch{return null}}
window.v3OpenFinish=async function(id){const v=await find(id);if(!v){window.showToast?.('Sessiya topilmadi.',true);return}const k='finish_'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_'),sch=String(v.customer_type||'').toLowerCase()==='school'||!!v.student_id;let html='<div class="modalHead"><div><h2 style="margin:0">Tugatish</h2><div class="muted">'+esc(v.plate||'')+' · '+esc(v.model||'')+'</div></div><button class="btn light" type="button" onclick="closeModal()">Yopish</button></div><div class="panel" style="margin-top:12px"><div class="kv"><div><span>O‘tgan vaqt</span><b id="sf-time-'+k+'">'+dur(seconds(v))+'</b></div><div><span>Summa</span><b id="sf-price-'+k+'" class="greenText">'+money(amount(v))+'</b></div><div><span>Mijoz</span><b>'+esc(v.student_name||v.driver_name||'Oddiy mijoz')+'</b></div><div><span>Toifa</span><b>'+ (sch?'AVTOSHKOLA':'CHASTNIY') +'</b></div></div></div>'+(sch?'':'<div class="fg"><label>To‘lov usuli</label><select id="sf-method-'+k+'"><option value="cash">Naqd</option><option value="terminal">Terminal</option><option value="mixed">Aralash</option></select></div><div id="sf-mix-'+k+'" class="formGrid hidden"><div class="fg"><label>Naqd</label><input id="sf-cash-'+k+'" type="number" min="0" value="0"></div><div class="fg"><label>Terminal</label><input id="sf-term-'+k+'" type="number" min="0" value="0"></div></div>')+'<div class="actions"><button class="btn green" type="button" onclick="finalFinish('+JSON.stringify(String(id))+')">Tugatishni tasdiqlash</button><button class="btn light" type="button" onclick="closeModal()">Bekor</button></div><div id="sf-err-'+k+'" class="err"></div>';if(typeof window.modal!=='function'){window.showToast?.('Tugatish oynasi mavjud emas.',true);return}window.modal(html);const m=$('sf-method-'+k);if(m)m.addEventListener('change',()=>{const b=$('sf-mix-'+k);if(b)b.classList.toggle('hidden',m.value!=='mixed')});const tick=()=>{$('sf-time-'+k)&&($('sf-time-'+k).textContent=dur(seconds(v)));$('sf-price-'+k)&&($('sf-price-'+k).textContent=money(amount(v)))};tick();clearInterval(window.__sfTimer);window.__sfTimer=setInterval(tick,1000)};
window.finalFinish=async function(id){const v=await find(id);if(!v)return;const k='finish_'+String(id).replace(/[^a-zA-Z0-9_-]/g,'_'),err=$('sf-err-'+k),sch=String(v.customer_type||'').toLowerCase()==='school'||!!v.student_id,a=Math.round(amount(v));let method=sch?'cash':($('sf-method-'+k)?.value||'cash'),cash=0,term=0;if(!sch&&method==='cash')cash=a;else if(!sch&&method==='terminal')term=a;else if(!sch){cash=Number($('sf-cash-'+k)?.value||0);term=Number($('sf-term-'+k)?.value||0);if(Math.abs(cash+term-a)>0.01){if(err)err.textContent='Naqd + Terminal summa hisoblangan narxga teng bo‘lishi kerak.';return}}try{await apiCall('/sessions/'+encodeURIComponent(id)+'/finish',{method:'POST',body:JSON.stringify({amount:a,paymentMethod:method,cashAmount:cash,terminalAmount:term})});clearInterval(window.__sfTimer);if(Array.isArray(window.active))window.active=window.active.filter(x=>String(x.id)!==String(id));window.closeModal?.();window.renderFinish?.();await window.v3LoadActive?.();window.renderWaitingQueue?.();window.showToast?.('Avtomobil muvaffaqiyatli tugatildi.')}catch(e){if(err)err.textContent=e.message||'Tugatishda xatolik'}};
window.v3InstructorDaily=async function(id){const date=typeof window.localDateISO==='function'?window.localDateISO(0):new Date().toISOString().slice(0,10);try{const d=await apiCall('/instructors/'+encodeURIComponent(id)+'/daily?date='+encodeURIComponent(date)),rows=Array.isArray(d?.rows)?d.rows:[],name=d?.instructor?.full_name||'Instruktor',body=rows.map((r,i)=>'<tr><td>'+(i+1)+'</td><td>'+esc(r.plate||'')+'</td><td>'+esc(r.student_name||r.driver_name||'Oddiy mijoz')+'</td><td>'+esc(r.school_name||'')+'</td><td>'+esc(r.group_name||'')+'</td><td>'+esc(r.started_at||'')+'</td><td>'+esc(r.finished_at||'')+'</td><td>'+dur(r.duration_seconds)+'</td><td>'+money(r.amount)+'</td></tr>').join('');const html='<html><head><meta charset="utf-8"><style>table{border-collapse:collapse}td,th{border:1px solid #999;padding:7px}</style></head><body><h2>'+esc(name)+' — '+date+'</h2><table><tr><th>#</th><th>Avtomobil</th><th>O‘quvchi/Mijoz</th><th>Avtoshkola</th><th>Guruh</th><th>Kirish</th><th>Tugash</th><th>Vaqt</th><th>Summa</th></tr>'+body+'</table></body></html>',blob=new Blob(['\\ufeff'+html],{type:'application/vnd.ms-excel;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(name.replace(/[^\\p{L}\\p{N}]+/gu,'_')||'instruktor')+'-'+date+'.xls';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);window.showToast?.('1 kunlik Excel tayyor.')}catch(e){window.showToast?.(e.message||'Excel yuklanmadi.',true)}};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',studentAuto,{once:true});else studentAuto();
})();
<\/script>`;
export default async function handler(req,res){if(req.method!=='GET'){res.statusCode=405;return res.end(JSON.stringify({error:'Method ruxsat etilmagan'}))}try{const html=await readFile(frontendFile,'utf8'),out=html.includes('id="avtodrom-final-fix"')?html:html.replace('</body>',PATCH+'</body>');res.statusCode=200;res.setHeader('Content-Type','text/html; charset=utf-8');res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');res.setHeader('Pragma','no-cache');res.end(out)}catch(e){res.statusCode=500;res.setHeader('Content-Type','application/json');res.end(JSON.stringify({error:'Frontend yuklanmadi'}))}}
