import crypto from 'node:crypto';
import { pool } from '../backend/src/db.js';

const send=(res,status,data)=>{if(res.headersSent)return;res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(data));};
const text=v=>String(v??'').trim();
function botToken(){return text(process.env.INSTRUCTOR_BOT_TOKEN||process.env.ADMIN_BOT_TOKEN||process.env.CUSTOMER_BOT_TOKEN);}
function telegramUser(initData){
 const token=botToken(); if(!token) throw Object.assign(new Error('INSTRUCTOR_BOT_TOKEN Vercelda sozlanmagan'),{statusCode:503});
 const p=new URLSearchParams(initData||''); const hash=p.get('hash'); if(!hash)return null;
 const pairs=[];for(const [k,v] of p.entries())if(k!=='hash')pairs.push([k,v]);pairs.sort((a,b)=>a[0].localeCompare(b[0]));
 const check=pairs.map(([k,v])=>`${k}=${v}`).join('\n');
 const secret=crypto.createHmac('sha256','WebAppData').update(token).digest();
 const expected=crypto.createHmac('sha256',secret).update(check).digest('hex');
 if(expected.length!==hash.length||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(hash)))return null;
 const age=Math.floor(Date.now()/1000)-Number(p.get('auth_date')||0);if(!Number.isFinite(age)||age>86400)return null;
 try{return JSON.parse(p.get('user')||'{}')}catch{return null;}
}
async function auth(req){
 const initData=text(req.headers?.['x-telegram-init-data']);const tg=telegramUser(initData);
 if(!tg?.id)throw Object.assign(new Error('Telegram sessiyasi topilmadi. Mini Appni bot ichidan oching.'),{statusCode:401});
 const r=await pool.query(`SELECT ip.id,ip.user_id,ip.bio,ip.experience_years,ip.rating,ip.total_reviews,ip.is_verified,ip.is_available,u.telegram_id,u.full_name,u.phone,u.is_active,u.is_blocked FROM instructor_profiles ip JOIN users u ON u.id=ip.user_id WHERE u.telegram_id=$1 AND u.role='instructor' LIMIT 1`,[Number(tg.id)]);
 const i=r.rows[0];if(!i)throw Object.assign(new Error('Siz instruktor sifatida topilmadingiz. Avval Admin tasdig‘idan o‘ting.'),{statusCode:403});
 if(!i.is_verified||!i.is_active||i.is_blocked)throw Object.assign(new Error('Instruktor akkauntingiz hali tasdiqlanmagan yoki bloklangan.'),{statusCode:403});
 return{tg,i};
}
async function me(req,res){const{tg,i}=await auth(req);const v=await pool.query(`SELECT plate,model,driver_name FROM vehicles WHERE avtodrom_instructor_id=$1 ORDER BY updated_at DESC NULLS LAST LIMIT 1`,[String(i.id)]);send(res,200,{ok:true,instructor:{id:i.id,user_id:i.user_id,telegram_id:i.telegram_id,full_name:i.full_name||tg.first_name||'Instruktor',phone:i.phone,bio:i.bio,experience_years:i.experience_years,rating:Number(i.rating||0),total_reviews:i.total_reviews,is_verified:i.is_verified,is_available:i.is_available,vehicle:v.rows[0]||null}});}
const bookingSelect=`SELECT b.id,b.instructor_id,b.customer_id,b.course_id,b.date,b.time,b.duration,b.status,b.price,b.payment_status,b.start_at,b.end_at,b.booking_date,b.customer_note,b.admin_note,b.instructor_note,b.confirmed_at,b.arrived_at,b.departed_at,b.created_at,b.updated_at,u.full_name AS customer_name,u.phone AS customer_phone,u.telegram_id AS customer_telegram_id,c.name AS course_name,c.duration_minutes AS course_duration,COALESCE(v.plate,'') AS vehicle_plate,COALESCE(v.model,'') AS vehicle_model,COALESCE(v.driver_name,'') AS vehicle_driver FROM bookings b LEFT JOIN users u ON u.id::text=b.customer_id LEFT JOIN courses c ON c.id::text=b.course_id LEFT JOIN LATERAL(SELECT plate,model,driver_name FROM vehicles vv WHERE vv.user_id::text=b.customer_id ORDER BY vv.updated_at DESC NULLS LAST LIMIT 1)v ON TRUE`;
async function bookings(req,res){const{i}=await auth(req);const u=new URL(req.url,'http://localhost');const date=u.searchParams.get('date');let sql=bookingSelect+' WHERE b.instructor_id=$1';const p=[String(i.id)];if(date==='today')sql+=` AND b.date=CURRENT_DATE`;else if(date){sql+=` AND b.date=$2`;p.push(date);}sql+=` ORDER BY b.date DESC,b.time DESC`;const r=await pool.query(sql,p);send(res,200,{ok:true,bookings:r.rows});}
async function stats(req,res){const{i}=await auth(req);const r=await pool.query(`SELECT COUNT(*) FILTER(WHERE date=CURRENT_DATE)::int today,COUNT(*) FILTER(WHERE date>=CURRENT_DATE-6)::int week,COUNT(*) FILTER(WHERE date>=CURRENT_DATE-29)::int month,COUNT(*) FILTER(WHERE date>=CURRENT_DATE-364)::int year,COUNT(*) FILTER(WHERE status IN ('confirmed','arrived','completed','no_show'))::int accepted FROM bookings WHERE instructor_id=$1`,[String(i.id)]);send(res,200,{ok:true,stats:r.rows[0]||{today:0,week:0,month:0,year:0,accepted:0}});}
async function changeStatus(req,res,id){const{ i }=await auth(req);const b=req.body&&typeof req.body==='object'?req.body:{};const action=text(b.action||b.status).toLowerCase();const found=await pool.query('SELECT * FROM bookings WHERE id=$1 AND instructor_id=$2 LIMIT 1',[String(id),String(i.id)]);if(!found.rows[0])return send(res,404,{ok:false,error:'Bron topilmadi'});const now=new Date().toISOString();let patch={updated_at:now};if(action==='arrived'||action==='keldi'){patch.status='arrived';patch.arrived_at=now;}else if(['departed','left','ketdi'].includes(action)){patch.status='completed';patch.departed_at=now;patch.end_at=found.rows[0].end_at||now;}else if(['confirmed','confirm'].includes(action)){patch.status='confirmed';patch.confirmed_at=now;}else if(action==='no_show')patch.status='no_show';else return send(res,400,{ok:false,error:'Noto‘g‘ri amal'});const cols=Object.keys(patch),vals=Object.values(patch);const set=cols.map((k,n)=>`${k}=$${n+1}`).join(',');vals.push(String(id),String(i.id));const r=await pool.query(`UPDATE bookings SET ${set} WHERE id=$${vals.length-1} AND instructor_id=$${vals.length} RETURNING *`,vals);send(res,200,{ok:true,booking:r.rows[0]});}
export default async function handler(req,res){try{const path=String(req.url||'').split('?')[0].replace(/\/+$/,'');if(req.method==='OPTIONS'){res.statusCode=204;return res.end();}if(path==='/api/instructor/me')return me(req,res);if(path==='/api/instructor/profile')return me(req,res);if(path==='/api/instructor/bookings')return bookings(req,res);if(path==='/api/instructor/dashboard'||path==='/api/instructor/statistics')return stats(req,res);const m=path.match(/^\/api\/instructor\/bookings\/([^/]+)\/status$/);if(m&&req.method==='PATCH')return changeStatus(req,res,decodeURIComponent(m[1]));return send(res,404,{ok:false,error:'Instructor API route topilmadi'});}catch(e){console.error('INSTRUCTOR TELEGRAM API:',e);send(res,e.statusCode||500,{ok:false,error:e.message||'Server xatosi'});}}
