import jwt from 'jsonwebtoken';
import crypto from 'node:crypto';
import { pool } from '../backend/src/db.js';

const JWT_SECRET=process.env.JWT_SECRET||'dev-only-change-me';
const text=v=>String(v??'').trim();
function json(res,status,data){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.end(JSON.stringify(data));}
function auth(req){try{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return null;return String(jwt.verify(h.slice(7),JWT_SECRET).sub||'')}catch{return null}}
async function body(req){if(req.body&&typeof req.body==='object')return req.body;if(typeof req.body==='string'){try{return JSON.parse(req.body)}catch{return {}}}return await new Promise((resolve,reject)=>{let r='';req.on('data',c=>r+=c);req.on('end',()=>{try{resolve(r?JSON.parse(r):{})}catch{reject(new Error('JSON noto‘g‘ri'))}});req.on('error',reject)})}
async function ensure(){await pool.query(`CREATE TABLE IF NOT EXISTS public.instructors(id text PRIMARY KEY DEFAULT gen_random_uuid()::text,profile_id text,active boolean NOT NULL DEFAULT true,approved boolean NOT NULL DEFAULT false,approved_at timestamptz,approved_by text,bio text,category text,experience_years integer NOT NULL DEFAULT 0,settings jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now())`)}
const clean=v=>text(v).toUpperCase().replace(/[^A-Z0-9]/g,'');
async function list(owner,id=null){let sql=`SELECT i.id,i.active,i.approved,i.bio AS full_name,i.settings, i.created_at,i.updated_at, i.settings->>'school_id' school_id,i.settings->>'group_id' group_id, COALESCE(v.plate,i.settings->>'vehicle_plate','') vehicle_plate,COALESCE(v.model,i.settings->>'vehicle_model','') vehicle_model,COALESCE(v.driver_name,'') driver_name,ds.name school_name,g.name group_name FROM public.instructors i LEFT JOIN driving_schools ds ON ds.id::text=i.settings->>'school_id' AND ds.owner_key=$1 LEFT JOIN school_groups g ON g.id::text=i.settings->>'group_id' AND g.owner_key=$1 LEFT JOIN LATERAL(SELECT plate,model,driver_name FROM vehicles vv WHERE vv.user_id=$1 AND vv.avtodrom_instructor_id=i.id ORDER BY vv.updated_at DESC NULLS LAST LIMIT 1)v ON true WHERE (i.settings->>'owner_key')=$1`;const p=[owner];if(id){p.push(String(id));sql+=` AND i.id=$2`}sql+=' ORDER BY lower(i.bio),i.created_at DESC';const r=await pool.query(sql,p);return id?(r.rows[0]||null):r.rows}
async function save(req,res,owner,id=null){const b=await body(req),name=text(b.fullName||b.name),schoolId=text(b.schoolId),plate=clean(b.vehiclePlate||b.plate),model=text(b.vehicleModel||b.model),active=b.active!==false;if(!name)return json(res,400,{error:'F.I.Sh. kerak'});if(!schoolId)return json(res,400,{error:'Avtoshkolani tanlang'});const school=await pool.query(`SELECT id,name FROM driving_schools WHERE id=$1 AND owner_key=$2 AND active=true`,[schoolId,owner]);if(!school.rows[0])return json(res,404,{error:'Avtoshkola topilmadi'});const c=await pool.connect();try{await c.query('BEGIN');const iid=id?String(id):crypto.randomUUID();if(id){const cur=await c.query(`SELECT id FROM public.instructors WHERE id=$1 AND (settings->>'owner_key')=$2 FOR UPDATE`,[iid,owner]);if(!cur.rows[0]){await c.query('ROLLBACK');return json(res,404,{error:'Instruktor topilmadi'})};await c.query(`UPDATE public.instructors SET bio=$1,active=$2,updated_at=now(),settings=COALESCE(settings,'{}'::jsonb)||$3::jsonb WHERE id=$4`,[name,active,JSON.stringify({owner_key:owner,school_id:schoolId}),iid])}else{const dup=await c.query(`SELECT id FROM public.instructors WHERE (settings->>'owner_key')=$1 AND lower(bio)=lower($2) AND active=true LIMIT 1`,[owner,name]);if(dup.rows[0]){await c.query('ROLLBACK');return json(res,409,{error:'Bu instruktor allaqachon mavjud'})};await c.query(`INSERT INTO public.instructors(id,active,approved,approved_at,approved_by,bio,settings,created_at,updated_at) VALUES($1,$2,true,now(),$3,$4,$5::jsonb,now(),now())`,[iid,active,owner,name,JSON.stringify({owner_key:owner,school_id:schoolId})])}
if(plate){const vr=await c.query(`SELECT id,plate,model,driver_name,avtodrom_instructor_id FROM vehicles WHERE user_id=$1 AND replace(upper(plate),' ','')=$2 LIMIT 1`,[owner,plate]);if(!vr.rows[0]){await c.query('ROLLBACK');return json(res,404,{error:'Bu avtomobil topilmadi. Avval avtomobilni bazaga qo‘shing.'})}const v=vr.rows[0],assigned=v.avtodrom_instructor_id?String(v.avtodrom_instructor_id):'';if(assigned&&assigned!==iid){await c.query('ROLLBACK');return json(res,409,{error:'Bu avtomobil boshqa instruktorga biriktirilgan'})}await c.query(`UPDATE vehicles SET avtodrom_instructor_id=NULL,updated_at=now() WHERE user_id=$1 AND avtodrom_instructor_id=$2 AND id<>$3`,[owner,iid,v.id]);await c.query(`UPDATE vehicles SET avtodrom_instructor_id=$1,model=COALESCE(NULLIF($2,''),model),updated_at=now() WHERE id=$3 AND user_id=$4`,[iid,model,v.id,owner]);await c.query(`UPDATE public.instructors SET settings=COALESCE(settings,'{}'::jsonb)||$1::jsonb,updated_at=now() WHERE id=$2`,[JSON.stringify({owner_key:owner,school_id:schoolId,vehicle_id:String(v.id),vehicle_plate:v.plate,vehicle_model:model||v.model||''}),iid])}
await c.query('COMMIT');return json(res,id?200:201,await list(owner,iid))}catch(e){try{await c.query('ROLLBACK')}catch{};console.error('FIXED INSTRUCTOR API',e);return json(res,500,{error:e.message||'Instruktor saqlanmadi'})}finally{c.release()}}
export default async function handler(req,res){if(req.method==='OPTIONS'){res.statusCode=204;return res.end()}const owner=auth(req);if(!owner)return json(res,401,{error:'Kirish talab qilinadi'});try{await ensure();const id=req.query?.id?String(req.query.id):null;if(req.method==='GET')return json(res,200,await list(owner,id));if(req.method==='POST')return save(req,res,owner,null);if(req.method==='PUT')return save(req,res,owner,id);if(req.method==='DELETE'){if(!id)return json(res,400,{error:'Instruktor ID kerak'});await pool.query(`UPDATE public.instructors SET active=false,updated_at=now() WHERE id=$1 AND (settings->>'owner_key')=$2`,[id,owner]);await pool.query(`UPDATE vehicles SET avtodrom_instructor_id=NULL,updated_at=now() WHERE user_id=$1 AND avtodrom_instructor_id=$2`,[owner,id]);return json(res,200,{ok:true})}return json(res,405,{error:'Method ruxsat etilmagan'})}catch(e){console.error(e);return json(res,500,{error:e.message||'Instruktor API xatosi'})}}
